// Auth types
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// Alert types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Opportunity types
export const GET_OPPORTUNITIES = 'GET_OPPORTUNITIES';
export const GET_OPPORTUNITY = 'GET_OPPORTUNITY';
export const ADD_OPPORTUNITY = 'ADD_OPPORTUNITY';
export const UPDATE_OPPORTUNITY = 'UPDATE_OPPORTUNITY';
export const DELETE_OPPORTUNITY = 'DELETE_OPPORTUNITY';
export const OPPORTUNITY_ERROR = 'OPPORTUNITY_ERROR';
export const CLEAR_OPPORTUNITY = 'CLEAR_OPPORTUNITY';
export const APPLY_OPPORTUNITY = 'APPLY_OPPORTUNITY';
export const UPDATE_APPLICATION_STATUS = 'UPDATE_APPLICATION_STATUS';

// User types
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';
export const GET_MY_APPLICATIONS = 'GET_MY_APPLICATIONS';
export const GET_COMPANY_OPPORTUNITIES = 'GET_COMPANY_OPPORTUNITIES';

// Error types
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
